export const SET_USER = 'SET_USER'
export const DELETE_USER = 'DELETE_USER'
export const SET_IS_AUTHENTICATING = 'SET_IS_AUTHENTICATING'
export const SET_AUTHENTICATION_ERR = 'SET_AUTHENTICATION_ERR'
